# Generated by Django 2.2.16 on 2022-05-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220521_1136'),
        ('reviews', '0003_auto_20220520_2217'),
    ]

    operations = [
    ]
