# Generated by Django 2.2.16 on 2022-05-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220521_1442'),
        ('reviews', '0004_merge_20220521_1316'),
    ]

    operations = [
    ]
